language: csharp
mono: latest
dotnet: 2.0.0
install:
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /t:Restore
  - msbuild /t:Build /p:Configuration=Release
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Pipelines.Tests.Integrations/bin/Release/netcoreapp2.0/Pipelines.Tests.Integrations.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Pipelines.Tests.Units/bin/Release/netcoreapp2.0/Pipelines.Tests.Units.dll
  - msbuild ./Pipelines/Pipelines.csproj /t:pack /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg
deploy:
  skip_cleanup: true
  provider: script
  script: 
    - nuget push ./Pipelines/bin/Debug/Pipelines.Net.*.nupkg -Verbosity detailed -ApiKey $NugetApiKey -Source https://api.nuget.org/v3/index.json
  on:
    branch: master
