language: csharp
mono: latest
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./Pipelines.Tests.Units/
  - dotnet test ./Pipelines.Tests.Integrations/
  - dotnet pack
deploy:
  skip_cleanup: true
  provider: script
  script: 
    - nuget push ./Pipelines/bin/Debug/Pipelines.Net.*.nupkg -Verbosity detailed -ApiKey $NugetApiKey -Source https://api.nuget.org/v3/index.json
  on:
    branch: master
