language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build ./Pipelines/ --framework netstandard2.0
  - dotnet test ./Pipelines.Tests.Units/
  - dotnet test ./Pipelines.Tests.Integrations/
